### ISSUE TITLE
Instantiation by reflection

### ISSUE THREAD

**Issue by ghost** [acvos/bubbles-container#1]
In SequentialBindingFactory, [newInstanceArgs](http://php.net/manual/en/reflectionclass.newinstanceargs.php) is used to instantiate classes.

Using this technique, there are a few things to be aware of (from the documentation comments):
- "Be aware that calling the method newInstanceArgs with an empty array will still call the constructor with no arguments. If the class has no constructor then it will generate an exception. You need to check if a constructor exists before calling this method or use try and catch to act on the exception."
- "It should be noted that the the values in the array are mapped to constructor arguments positionally, rather than by name, so using an associative array will not make any difference."

**Comment by ghost** [comment]
Using PHP 5.6, it would be possible to use argument unpacking to achieve the same thing without reflection:

http://php.net/manual/en/migration56.new-features.php#migration56.new-features.splat

**Comment by acvos** [comment]
Positional! That's the word I should use instead of Sequential.

I don't think we're going to require php 5.6 just yet. 

And yes, we're going to add some other functionality to support parameter name binding

**Comment by ghost** [comment]
Awesome! :)

Bubbles is really cool. Or.... Bubbles _are_ really cool?
![image](https://cloud.githubusercontent.com/assets/4805057/6567266/f2851e4a-c681-11e4-89ac-c6294a9bf47c.png)

To check that a constructor exists and that it can be called, `is_callable` works well:
`is_callable(['\My\Class', '__construct']) === true`

**Comment by ghost** [comment]
Added a comment to https://github.com/acvos/bubbles-container/commit/05ef9370da5c0c9ada5872b5fcf3132dd594c37f

**Comment by ghost** [comment]
I think this is fixed now!

**Comment by acvos** [comment]
Woo-hoo
