### ISSUE TITLE
Setter injection

### ISSUE THREAD

**Issue by ghost** [acvos/bubbles-container#2]
In some cases, it is preferable to use setter injection over constructor injection.

Bubbles should support setter injection! :)

**Comment by acvos** [comment]
Also, I believe we should be able to bind injected dependencies using their names, not only their order

**Comment by ghost** [comment]
Niiiice! :+1:

It's an interesting idea that the configuration doesn't specify at all how a dependency is injected. It felt weird at first... but it actually makes total sense! It's just an implementation detail.

For the setter injection part, I also wondered if some people would like public variable injection; but that's such a bad practice that I don't think it should be allowed.
